# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - netstandard

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs: 
    command: 'pack'
    configuration: 'Release'
    packagesToPack: 'qif/qif.csproj'
    nobuild: true
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '1'
    verbosityPack: 'normal'
- task: NuGetCommand@2
  displayName: 'Push nuget package to DevOps feed'
  inputs:
    command: push
    publishVstsFeed: 'Lien'
