# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- netstandard

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  version: '1.0.0'
  major: '1'
  minor: '0'
  patch: '0'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCLI@2
  displayName: 'dotnet pack'
  inputs: 
    command: 'pack'
    configuration: 'release'
    packagesToPack: 'qif/qif.csproj'
    nobuild: true
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '1'
- task: NuGetCommand@2
  displayName: 'Push nuget package to DevOps feed'
  inputs:
    command: push
    publishVstsFeed: 'Lien'
